---
- hosts: multi
  become: no

  handlers:
  - name: set docker script permission
    file:
      path: /home/vagrant/get-docker.sh
      mode: '0755'
    notify: get docker script permission
  - name: get docker script permission
    command: "ls -lh /home/vagrant/get-docker.sh"
    register: file_detail
    notify: print docker script permission
  - name: print docker script permission
    debug:
      msg: "/home/vagrant/get-docker.sh : {{ file_detail.stdout }}"

  tasks:
  - name: Download docker script installation
    get_url:
      url: https://get.docker.com 
      dest: /home/vagrant/get-docker.sh
    notify: set docker script permission