---
- name: Create user group
  ansible.builtin.group:
    name: "{{ item.group }}"
    state: present
  with_items: "{{ users }}"

- name: Create user
  ansible.builtin.user:
    name: "{{ item.name }}"
    state: present
    shell: "{{ item.shell }}"
    create_home: true
    group: "{{ item.group }}"
  with_items: "{{ users }}"